issue with bcrypt at the moment
uwblueprint/building-up-server pull request #15
Opened 2020-09-26 20:29 UTC by Anand-Issac

- created frame for registering users, logging in, and getting active user using cookies

2020-09-27 19:02 UTC, allyonthego requested changes

2020-09-27 19:02 UTC, allyonthego commented on src/keys.env
> +ACCESS_TOKEN_SECRET=B07E607904984E372D5BFE7F4A4479EC45669D01F18624ACE5F1E0C9278D4504
Should this be in the commit at all?

2020-09-27 19:02 UTC, allyonthego commented on src/resolvers/auth.js
> +      console.log("hello");
Guessing this is just for testing?

2020-09-27 22:57 UTC, faizaanmadhani commented on src/keys.env
> +ACCESS_TOKEN_SECRET=B07E607904984E372D5BFE7F4A4479EC45669D01F18624ACE5F1E0C9278D4504
This will need to be purged from the commit history before we merge.

2020-10-05 01:12 UTC, michaelmeng998 approved these changes
just a small nitpick, otherwise lgtm based off the fact Faizaan will be purging the keys in the .env file.

2020-10-05 01:12 UTC, michaelmeng998 commented on src/resolvers/auth.js
> +        const valid = bcrypt.compareSync(password, user.password); // true
[nitpick]: What's the comment for?

2020-10-16 00:43 UTC, raveen-singh reviewed
Looks good.

2020-10-16 00:44 UTC, raveen-singh approved these changes

2020-10-16 00:45 UTC, merged